name: TheDispatchTests

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (qa/qa2/dev)'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          ignore_sha: true
          access_token: ${{ github.token }}
      
      - name: Sleep for 60 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      
      - name: Run tests in QA
        if: github.event.action == 'qa_tests' || github.event.inputs.environment == 'qa'
        run: echo Hello, qa tests!
        
      - name: Run tests in DEV
        if: github.event.action == 'dev_tests' || github.event.inputs.environment == 'dev'
        run: echo Hello, dev tests!

