name: TheDispatchTests

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (qa/kkq/dev/ddd)'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          ignore_sha: true
          access_token: ${{ github.token }}

      - name: Install Cypress
        run: npm install
      
      - name: Run tests in QA
        if: >
          github.event.action == 'qa_tests' || 
          github.event.action == 'kkq_tests' || 
          github.event.inputs.environment == 'qa' || 
          github.event.inputs.environment == 'kkq'
        run: |   
            npx cypress run --spec cypress/integration/1-getting-started/*.js --browser chrome --headless --env allure=true,configFile=qa
        continue-on-error: true
        
      - name: Run tests in DEV
        if: >
          github.event.action == 'dev_tests' || 
          github.event.action == 'ddd_tests' || 
          github.event.inputs.environment == 'dev' || 
          github.event.inputs.environment == 'ddd'
        run: |   
            npx cypress run --spec cypress/integration/1-getting-started/*.js --browser chrome --headless --env allure=true,configFile=dev
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
                
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
                    
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: qlimlass.github.io/allure-history/${{ github.run_number }}
