name: TheDispatchTests

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (qa/kkq/dev/ddd)'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          ignore_sha: true
          access_token: ${{ github.token }}
      
      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      
      - name: Run tests in QA
        if: >
          github.event.action == 'qa_tests' || 
          github.event.action == 'kkq_tests' || 
          github.event.inputs.environment == 'qa' || 
          github.event.inputs.environment == 'kkq'
        run: echo Hello, qa tests!
        
      - name: Run tests in DEV
        if: >
          github.event.action == 'dev_tests' || 
          github.event.action == 'ddd_tests' || 
          github.event.inputs.environment == 'dev' || 
          github.event.inputs.environment == 'ddd'
        run: echo Hello, dev tests!

