name: TheDispatchTests

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Run tests in QA
        if: github.event.action == 'qa_tests'
        run: echo Hello, qa tests!
        
      - name: Run tests in DEV
        if: github.event.action == 'dev_tests'
        run: echo Hello, dev tests!

