name: TheQATests

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        if: github.event.action = 'qa_tests'
        run: echo Hello, QA tests!
